name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          path: build/simple-calendar-*.zip
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm run setup
      - run: npm run build
